name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build a Debug Apk
      run: bash ./gradlew assembleDebug --stacktrace
    - name: upload artifact to Firebase App Distribution
      uses: manishkummar21/FirebaseAppDistribution-GithubAction@master
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        releaseNotes: Testing App Disturbution
        groups: QA
        file: app/build/outputs/apk/debug/app-debug.apk 
